/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hu.reqeng.pizza.api;


import java.util.List;

import hu.reqeng.pizza.model.ChooseOfferFailureResponse;
import hu.reqeng.pizza.model.ChooseOfferRequest;
import hu.reqeng.pizza.model.ChooseOfferSuccessResponse;
import hu.reqeng.pizza.model.Offer;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-14T22:52:33.799Z")

@Api(value = "offers", description = "the offers API")
@RequestMapping(value = "/v1")
public interface OffersApi {

    @ApiOperation(value = "Choose an offer", nickname = "chooseOffer", notes = "", response = ChooseOfferSuccessResponse.class, tags={ "offer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Offer selected successfully", response = ChooseOfferSuccessResponse.class),
        @ApiResponse(code = 404, message = "Offer not exists", response = ChooseOfferFailureResponse.class),
        @ApiResponse(code = 410, message = "Offer selected already", response = ChooseOfferFailureResponse.class),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/offers/{offerId}",
        method = RequestMethod.POST)
    ResponseEntity<Object> chooseOffer(@ApiParam(value = "The id of the offer",required=true) @PathVariable("offerId") String offerId, @ApiParam(value = "" ,required=true )  @Valid @RequestBody ChooseOfferRequest itemToChoose);

}
